services:

  redis:
    image: redis:7.2.1-alpine
    command: redis-server --requirepass $3nh4! --maxmemory 1gb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
  
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src
      - ./gopkg:/go/pkg/mod
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: $3nh4!